export type BudgetStyle = 'smart_budget' | 'balanced_experience' | 'premium_comfort';

export type TravelStyle =
  | 'first_time_must_sees'
  | 'explore_like_local'
  | 'relaxed_safe'
  | 'history_culture'
  | 'food_local'
  | 'photo_video'
  | 'romantic'
  | 'family_friendly'
  | 'adventure';

export type ReadinessStatus = 'ready' | 'needs_review' | 'not_set' | 'suggested';

export type ReadinessCategory =
  | 'entry_documents'
  | 'connectivity'
  | 'arrival_transport'
  | 'accommodation'
  | 'budget'
  | 'safety'
  | 'itinerary'
  | 'packing';

export type TrustSourceType =
  | 'official_recommended'
  | 'estimated'
  | 'sample_data'
  | 'provider_ready';

export type TrustConfidence = 'high' | 'medium' | 'low';

export type CostLevel = 'low' | 'medium' | 'high';

export interface TrustMeta {
  sourceType: TrustSourceType;
  confidence: TrustConfidence;
  lastCheckedLabel: string;
}

export interface SourceLink {
  id: string;
  title: string;
  description: string;
  url: string;
  sourceType: TrustSourceType;
  confidence: TrustConfidence;
  isExternal: boolean;
  isPlaceholder?: boolean;
  /** Overrides the sourceType-derived badge label when set. */
  badgeLabel?: string;
}

export interface ReadinessItem {
  id: string;
  title: string;
  status: ReadinessStatus;
  category: ReadinessCategory;
  description: string;
  detailRoute?: string;
  trust: TrustMeta;
}

export interface ReadinessState {
  items: ReadinessItem[];
  score: number;
}

export interface Activity {
  id: string;
  title: string;
  description: string;
  category: string;
  estimatedDuration: string;
  estimatedCostLevel: CostLevel;
  transportNote: string;
  whyItFits: string;
  trust: TrustMeta;
  isVisited?: boolean;
  isSaved?: boolean;
  coordinates?: { latitude: number; longitude: number };
}

export interface ItineraryDay {
  day: number;
  title: string;
  theme: string;
  summary: string;
  morning: Activity[];
  afternoon: Activity[];
  evening: Activity[];
  alternatives: Activity[];
  estimatedCostLevel: CostLevel;
  transportSuggestion: string;
}

export interface Place {
  id: string;
  name: string;
  category: string;
  city: string;
  shortDescription: string;
  isVisited?: boolean;
  isFavorite?: boolean;
  userNote?: string;
  coordinates?: { latitude: number; longitude: number };
}

export interface Trip {
  id: string;
  destinationId: string;
  destinationName: string;
  durationDays: number;
  budgetStyle: BudgetStyle;
  travelStyle: TravelStyle;
  expectationNote?: string;
  readiness: ReadinessState;
  itinerary: ItineraryDay[];
  savedPlaces: Place[];
  visitedPlaces: Place[];
  createdAt: string;
}

export interface Destination {
  id: string;
  name: string;
  subtitle: string;
  emoji: string;
  coverDescription: string;
  isAvailable: boolean;
  badge?: string;
}

/* ── Future-ready source / freshness metadata ──
 * Structured for later official/provider source tracking, last-checked
 * dates, confidence levels and manual review workflows. No live freshness
 * monitoring is implemented in V1 — these are static sample values. */
export interface SourceMeta {
  sourceType: 'official' | 'provider' | 'estimated' | 'sample';
  sourceUrl?: string;
  lastCheckedAt?: string;
  confidence: 'high' | 'medium' | 'low';
  updateFrequency?: 'daily' | 'weekly' | 'monthly';
  requiresManualReview?: boolean;
}

/* ── Destination registry (search-first welcome) ── */

export type DestinationStatus = 'supported' | 'coming_soon';
export type PackType = 'verified' | 'basic_draft_available' | 'coming_soon';

export interface DestinationRegistryItem {
  id: string;
  name: string;
  country: string;
  emoji: string;
  aliases: string[];
  status: DestinationStatus;
  packType: PackType;
  shortDescription: string;
  sourceMeta: SourceMeta;
}

/* ── Basic draft / unsupported destination types ── */

export interface BasicDraftSection {
  title: string;
  summary: string;
  confidence: 'low' | 'medium';
  sourceReminder: string;
}

export interface BasicDraftResult {
  /** UUID from Supabase row — present when draft came from DB or was freshly saved. */
  id?: string;
  destination: string;
  /** URL-safe slug, e.g. "japan" or "new-york". */
  destinationSlug?: string;
  status: 'basic_draft';
  verified: false;
  generatedAt: string;
  updatedAt?: string;
  lastUsedAt?: string;
  /** How many times this cached draft has been served. */
  usageCount?: number;
  confidence: 'low' | 'medium';
  /**
   * Origin of the draft:
   *  openrouter           – freshly generated by AI, saved to DB
   *  database_cache       – served from Supabase cache (no OpenRouter call)
   *  openrouter_uncached  – AI generated but DB save failed; draft shown but not cached
   *  mock                 – local fallback when Supabase is not configured
   */
  provider?: 'openrouter' | 'database_cache' | 'openrouter_uncached' | 'mock';
  /** The model used when provider is openrouter or openrouter_uncached. */
  model?: string;
  /** Present when provider is openrouter_uncached — safe summary of the DB save error. */
  cacheError?: string;
  disclaimer: string;
  draftId?: string;
  sections: BasicDraftSection[];
}

export interface DestinationNotificationPayload {
  destination: string;
  action: 'request_pack' | 'basic_draft_created' | 'basic_draft_used' | 'basic_draft_created_uncached';
  source: 'welcome_search' | 'unsupported_destination_panel';
  requestedAt: string;
  status?: 'requested' | 'draft_created' | 'draft_used' | 'draft_created_uncached' | 'failed';
  userNote?: string;
  draftId?: string;
  destinationSlug?: string;
  provider?: string;
  model?: string;
  cacheError?: string;
  appVersion?: string;
  platform?: string;
}

export type RescueScenario =
  | 'closed'
  | 'crowded'
  | 'expensive'
  | 'tired'
  | 'food'
  | 'weather'
  | 'safer_route'
  | 'return_to_hotel'
  | 'replan_today';

export interface AlternativeActivity extends Activity {
  reason: string;
  distance: string;
  openStatus: 'open' | 'closed' | 'unknown';
}

/* ── Preparation checklist types ── */

export interface RecommendedCard {
  description: string;
  steps: string[];
}

export interface PrepOption {
  id: string;
  title: string;
  bestFor: string;
  pros: string[];
  cons: string[];
  watchOut?: string;
  estimatedCost: string;
  link?: SourceLink;
}

export interface PrepChecklist {
  id: string;
  title: string;
  icon: string;
  category: ReadinessCategory;
  shortDescription: string;
  detailId: string;
  status: ReadinessStatus;
  trust: TrustMeta;
  details: {
    summary: string;
    recommendedCard?: RecommendedCard;
    whatYouNeedToKnow: string[];
    optionsSectionTitle?: string;
    options?: PrepOption[];
    beforeYouGo: string[];
    warning?: string | null;
    sourceLinks: SourceLink[];
    ctaHelper?: string;
    ctaLabel?: string;
  };
}
